spring:
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  sql:
    init:
      mode: never

